"""Monad blockchain bridge for ParallelPulse.

Translates FaultSignal objects from the Python simulation layer into
signed Ethereum transactions sent to the EnergyMarket contract on Monad.

Platform note: Must run on Linux/macOS/WSL2 (not native Windows).
"""
from __future__ import annotations

import logging
import os
import time
from typing import Any

from web3 import Web3
from web3.contract import Contract
from web3.types import TxReceipt

from .schemas import FaultSignal, SOCReading

logger = logging.getLogger(__name__)

# Minimal ABI — only the functions and events ParallelPulse uses.
# Full ABI is generated by `forge build && cat out/EnergyMarket.sol/EnergyMarket.json`.
ENERGY_MARKET_ABI: list[dict] = [
    {
        "type": "function",
        "name": "activateEmergency",
        "inputs": [
            {"name": "busId", "type": "uint256"},
            {"name": "criticalLoads", "type": "address[]"},
        ],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "submitEnergyOffer",
        "inputs": [
            {"name": "amount", "type": "uint256"},
            {"name": "price", "type": "uint256"},
        ],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "settleTransfer",
        "inputs": [
            {"name": "bess", "type": "address"},
            {"name": "load", "type": "address"},
            {"name": "amount", "type": "uint256"},
        ],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "deactivateEmergency",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "emergencyMode",
        "inputs": [],
        "outputs": [{"type": "bool"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "earnings",
        "inputs": [{"name": "", "type": "address"}],
        "outputs": [{"type": "uint256"}],
        "stateMutability": "view",
    },
    {
        "type": "event",
        "name": "EmergencyActivated",
        "inputs": [
            {"name": "busId", "type": "uint256", "indexed": True},
            {"name": "criticalLoads", "type": "address[]", "indexed": False},
            {"name": "timestamp", "type": "uint256", "indexed": False},
        ],
    },
    {
        "type": "event",
        "name": "TransferSettled",
        "inputs": [
            {"name": "bess", "type": "address", "indexed": True},
            {"name": "load", "type": "address", "indexed": True},
            {"name": "amount", "type": "uint256", "indexed": False},
            {"name": "cost", "type": "uint256", "indexed": False},
        ],
    },
]


def _load_name_to_address(load_id: str) -> str:
    """Derive a deterministic Ethereum address from a load name.

    Uses keccak256 of the UTF-8 encoded name, taking the last 20 bytes.
    This is a hackathon-grade approach — production systems would use
    a proper address registry.
    """
    raw = Web3.keccak(text=load_id)
    return Web3.to_checksum_address("0x" + raw.hex()[-40:])


class MonadBridge:
    """Bridge between the Python simulation layer and the Monad EnergyMarket contract.

    Args:
        rpc_url: Monad HTTP RPC endpoint.
        contract_address: Deployed EnergyMarket contract address.
        private_key: Hex-encoded private key for transaction signing.
        abi: Optional override for the contract ABI.
        gas_price_multiplier: Safety multiplier applied to the estimated gas price.
            Defaults to 2.0 to avoid underpriced transactions on Monad testnet.
    """

    def __init__(
        self,
        rpc_url: str,
        contract_address: str,
        private_key: str,
        abi: list[dict] | None = None,
        gas_price_multiplier: float = 2.0,
    ) -> None:
        self._w3 = Web3(Web3.HTTPProvider(rpc_url))
        self._account = self._w3.eth.account.from_key(private_key)
        self._contract: Contract = self._w3.eth.contract(
            address=Web3.to_checksum_address(contract_address),
            abi=abi or ENERGY_MARKET_ABI,
        )
        self._gas_price_multiplier = gas_price_multiplier
        logger.info(
            "MonadBridge initialised. Address: %s, Contract: %s",
            self._account.address,
            contract_address,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def emit_fault_signal(self, signal: FaultSignal) -> str:
        """Send an activateEmergency transaction to Monad.

        Args:
            signal: Structured fault event from IEEE33FaultDetector.

        Returns:
            Transaction hash as a hex string.
        """
        critical_addresses = [_load_name_to_address(lid) for lid in signal.critical_load_ids]
        tx_hash = self._send_tx(
            self._contract.functions.activateEmergency(signal.bus_id, critical_addresses)
        )
        logger.info(
            "EmergencyActivated tx sent. Bus: %d, Fault: %s, TxHash: %s",
            signal.bus_id,
            signal.fault_type,
            tx_hash,
        )
        return tx_hash

    def submit_energy_offer(self, amount_wh: int, price_wei: int) -> str:
        """Submit a BESS energy offer to the contract.

        Args:
            amount_wh: Energy amount in Watt-hours.
            price_wei: Price per Wh in wei (before emergency multiplier).

        Returns:
            Transaction hash as a hex string.
        """
        tx_hash = self._send_tx(
            self._contract.functions.submitEnergyOffer(amount_wh, price_wei)
        )
        logger.info("SubmitOffer tx sent. Amount: %d Wh, Price: %d wei, TxHash: %s",
                    amount_wh, price_wei, tx_hash)
        return tx_hash

    def settle_transfer(self, bess_address: str, load_name: str, amount_wh: int) -> str:
        """Settle an energy transfer between a BESS device and a load.

        Args:
            bess_address: Ethereum address of the BESS device.
            load_name: Human-readable load name (converted to address).
            amount_wh: Energy amount transferred in Wh.

        Returns:
            Transaction hash as a hex string.
        """
        load_address = _load_name_to_address(load_name)
        tx_hash = self._send_tx(
            self._contract.functions.settleTransfer(
                Web3.to_checksum_address(bess_address), load_address, amount_wh
            )
        )
        logger.info("SettleTransfer tx sent. BESS: %s, Load: %s, TxHash: %s",
                    bess_address, load_name, tx_hash)
        return tx_hash

    def deactivate_emergency(self) -> str:
        """Deactivate emergency mode on the contract."""
        tx_hash = self._send_tx(self._contract.functions.deactivateEmergency())
        logger.info("EmergencyDeactivated tx sent. TxHash: %s", tx_hash)
        return tx_hash

    def get_emergency_mode(self) -> bool:
        """Read the current emergencyMode boolean from the contract."""
        return bool(self._contract.functions.emergencyMode().call())

    def get_earnings(self, bess_address: str) -> int:
        """Read accumulated earnings (wei) for a BESS address."""
        return int(
            self._contract.functions.earnings(
                Web3.to_checksum_address(bess_address)
            ).call()
        )

    def poll_events(self, from_block: int | str = "latest") -> list[dict[str, Any]]:
        """Poll recent contract events for the backend relay.

        Args:
            from_block: Starting block number or "latest".

        Returns:
            List of raw event dicts with 'event', 'args', 'blockNumber'.
        """
        results: list[dict] = []
        try:
            emergency_filter = self._contract.events.EmergencyActivated.create_filter(
                fromBlock=from_block
            )
            results.extend(emergency_filter.get_all_entries())
        except Exception as exc:  # noqa: BLE001
            logger.warning("Failed to poll EmergencyActivated events: %s", exc)
        try:
            transfer_filter = self._contract.events.TransferSettled.create_filter(
                fromBlock=from_block
            )
            results.extend(transfer_filter.get_all_entries())
        except Exception as exc:  # noqa: BLE001
            logger.warning("Failed to poll TransferSettled events: %s", exc)
        return results

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _send_tx(self, fn: Any, max_retries: int = 3) -> str:
        """Sign and send a contract function call transaction.

        Retries up to max_retries times with exponential back-off on
        transient RPC errors.

        Args:
            fn: web3.py contract function prepared for calling.
            max_retries: Maximum retry attempts before re-raising.

        Returns:
            Transaction hash as a hex string.
        """
        gas_price = int(self._w3.eth.gas_price * self._gas_price_multiplier)
        nonce = self._w3.eth.get_transaction_count(self._account.address, "pending")
        tx = fn.build_transaction(
            {
                "from": self._account.address,
                "nonce": nonce,
                "gasPrice": gas_price,
            }
        )
        # Estimate gas with a 20% buffer
        try:
            estimated = self._w3.eth.estimate_gas(tx)
            tx["gas"] = int(estimated * 1.2)
        except Exception:  # noqa: BLE001
            tx["gas"] = 300_000  # fallback

        signed = self._account.sign_transaction(tx)

        for attempt in range(max_retries):
            try:
                tx_hash = self._w3.eth.send_raw_transaction(signed.raw_transaction)
                return tx_hash.hex()
            except Exception as exc:  # noqa: BLE001
                if attempt < max_retries - 1:
                    wait = 2 ** attempt
                    logger.warning("Tx send failed (attempt %d): %s — retrying in %ds",
                                   attempt + 1, exc, wait)
                    time.sleep(wait)
                else:
                    raise
        raise RuntimeError("unreachable")


def from_env() -> MonadBridge:
    """Construct a MonadBridge from environment variables.

    Required environment variables (read from project-root .env or shell):
        RPC_URL:          Monad / Anvil HTTP RPC endpoint.
        CONTRACT_ADDRESS: Deployed EnergyMarket address.
        PRIVATE_KEY:      Hex-encoded private key (with or without 0x prefix).
    """
    return MonadBridge(
        rpc_url=os.environ["RPC_URL"],
        contract_address=os.environ["CONTRACT_ADDRESS"],
        private_key=os.environ["PRIVATE_KEY"],
    )
